baseURL = 'https://itska.lol/'
languageCode = 'en'
title = 'itska'
theme = 'risotto'
DefaultContentLanguage = 'en'
enableInlineShortcodes = true


sectionPagesMenu = "main"
ignoreErrors = ['error-remote-getjson']

[params]
noindex = false

[params.theme]
palette = 'base16-light'

[params.about]
title = '> itska'
description = 'resident brain scratcher'



[[params.socialLinks]]
icon = 'fa-brands fa-github'
title = 'GitHub'
url = 'https://github.com/xitska'

[[params.socialLinks]]
icon = 'fa-solid fa-envelope'
title = 'Email'
url = 'mailto:harry@itska.lol'

[[params.socialLinks]]
icon = 'fa-brands fa-x'
title = 'X'
url = 'https://x.com/xitska'

[[params.socialLinks]]
icon = 'fa-brands fa-mastodon'
title = 'Mastodon'
url = 'https://infosec.exchange/@xitska'
rel = 'me'
